# Generated by Django 4.2.30 on 2026-07-23 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0002_training_plan_phase_9'),
        ('companies', '0002_store_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeling', models.CharField(choices=[('easy', '轻松'), ('moderate', '适中'), ('hard', '吃力')], max_length=10)),
                ('improvement_note', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('class_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='training.classrecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_feedbacks',
            },
        ),
    ]
