# Generated by Django 4.2.30 on 2026-07-22 06:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_courseschedule_coursebooking_and_more'),
        ('attendance', '0001_initial'),
        ('companies', '0002_store_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=10)),
                ('stages', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('personal', '个人'), ('company_shared', '公司共享')], max_length=20)),
                ('pose_sequence', models.JSONField()),
                ('notes_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('course_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_templates', to='courses.coursetemplate')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_templates',
            },
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_date', models.DateField()),
                ('theme', models.CharField(max_length=200)),
                ('session_number', models.PositiveIntegerField(default=1)),
                ('pose_sequence', models.JSONField(default=dict)),
                ('trainer_notes', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('completion_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('improvement_tags', models.JSONField(default=list)),
                ('next_focus', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '完成')], default='draft', max_length=10)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_record', to='attendance.attendance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_records', to='training.trainingplan')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_records', to='courses.courseschedule')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_records', to='companies.store')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_records', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_records',
                'ordering': ['-class_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=10)),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('annotations', models.JSONField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('class_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='training.classrecord')),
            ],
            options={
                'db_table': 'class_media',
            },
        ),
    ]
