# Generated by Django 4.2.30 on 2026-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('company_admin', '公司管理员'), ('store_manager', '门店经理'), ('trainer', '教练'), ('student', '学员')], max_length=20),
        ),
    ]
