# Generated by Django 4.2.30 on 2026-07-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_store_room'),
        ('accounts', '0003_remove_user_company_id_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_id',
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.store'),
        ),
    ]
