# Generated by Django 4.2.30 on 2026-07-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
