# Generated by Django 4.2.30 on 2026-07-22 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetemplate',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddConstraint(
            model_name='coursetemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_course_template_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='coursetemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 'private'), _negated=True), ('max_capacity', 1), _connector='OR'), name='private_course_capacity_is_one'),
        ),
    ]
