# Generated by Django 4.2.30 on 2026-07-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_store_room'),
        ('courses', '0002_alter_coursetemplate_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booking_deadline', models.DateTimeField(blank=True, null=True)),
                ('schedule_mode', models.CharField(choices=[('single', '单次'), ('recurring', '周期')], default='single', max_length=10)),
                ('recurring_rule', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', '已发布'), ('cancelled', '已取消'), ('completed', '已完成')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('course_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetemplate')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.room')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.store')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_schedules',
                'ordering': ['course_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', '已预约'), ('cancelled', '已取消')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courses.courseschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_bookings',
            },
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('room', 'course_date', 'start_time'), name='unique_room_schedule_start'),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('trainer', 'course_date', 'start_time'), name='unique_trainer_schedule_start'),
        ),
        migrations.AddConstraint(
            model_name='coursebooking',
            constraint=models.UniqueConstraint(fields=('schedule', 'student'), name='unique_schedule_student_booking'),
        ),
    ]
