# Generated by Django 4.2.30 on 2026-07-22 01:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_store_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('member_card_type', models.CharField(choices=[('count', '次卡'), ('month', '月卡'), ('quarter', '季卡'), ('year', '年卡'), ('stored', '储值卡')], max_length=10)),
                ('member_card_start', models.DateField()),
                ('member_card_expire', models.DateField(db_index=True)),
                ('member_card_balance', models.IntegerField(default=0)),
                ('health_notes', models.TextField()),
                ('injury_history', models.TextField()),
                ('contraindications', models.TextField()),
                ('training_goal', models.CharField(max_length=255)),
                ('preferred_style', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('home_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='companies.store')),
                ('primary_trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='BodyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_date', models.DateField()),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('posture_spine', models.CharField(blank=True, max_length=100)),
                ('posture_pelvis', models.CharField(blank=True, max_length=100)),
                ('posture_shoulder', models.CharField(blank=True, max_length=100)),
                ('flexibility_score', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('core_strength_score', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('photos', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='members.studentprofile')),
            ],
            options={
                'db_table': 'body_assessments',
                'ordering': ['-assess_date'],
            },
        ),
    ]
