# Generated by Django 4.2.30 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='member_card_active',
            field=models.BooleanField(default=True),
        ),
    ]
